#!/usr/bin/env bash
# Script to configure your nginx server so that redirect_me 
# is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html:wq
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "36i $redirect" /etc/nginx/sites-available/default
sudo service nginx restart
