#!/usr/bin/bash
# Configure web server similar to a previous project
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server /a add_header X-Served-By\"$HOSTNAME\";" /etc/nginx/sites-available/default
sudo service nginx restart
