#!/usr/bin/env bash
# Bash script to install and configure HAProxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg
sudo printf %s "
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option  redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stat
    balance roundrobin
    option httpclose
    option forwardfor
    server 2384-web-01 3.89.119.219:80 check
    server 2384-web-02 35.185.52.50:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
