#!/usr/bin/env bash
# This script displays:
# To infinity and beyond
# with sleep 3 in between each iterartion
# I am invincible!!! when recieving a SIGTERM signal
trap "echo 'I am invincible!!!'" SIGTERM

while :
do
    echo "To infinity and beyond"
    sleep 2
done
