#!/usr/bin/env bash
# This script displays "Holberton School" 10 times but in position 9 will say "Hi"
i=0
while ((i < 10))
do
    if ((i == 9))
    then
        echo "Hi"
    fi
    echo "Holberton School"
    ((i = i + 1))
done
