#!/usr/bin/env bash
# This script displays "Holberton School" 10 times
# but in positio 9 will say "Hi"
i=1
while ((i <= 10))
do
    if ((i == 9))
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    ((i = i + 1))
done
