#!/usr/bin/env bash
# This script displays 1 - 20 using while loop
# will display bad luck from China for 4
# will display bad luck from Japan for 9
# whil display bad luck from Italy for 17
i=1
while ((i <= 20))
do
    if ((i == 4))
    then
        echo $i
        echo "bad luck from China"
    elif ((i == 9))
    then
        echo $i
        echo "bad luck from Japan"
    elif ((i == 17))
    then
        echo $i
        echo "bad luck from Italy"
    else
        echo $i
    fi
    ((i = i + 1))
done
