#!/usr/bin/env bash
# This script displays 1 - 20 using while loop
# will display bad luck from China for 4
# will display bad luck from Japan for 9
# whil display bad luck from Italy for 17
i=1
while ((i <= 20))
do
    case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    ((i = i + 1))
done
