#!/usr/bin/env bash
# This script displaiys the time for 12 hours and 59 minutes
hours=0
while ((hours < 12))
do
    echo "Hour: $hours"
    minutes=1
    while ((minutes < 60))
    do
        echo "$minutes"
        ((minutes = minutes +  1))
    done
    ((hours = hours + 1))
done
