#!/usr/bin/env bash
# This script displays
# The content of the current directory
# In a lisr format
# Where only the part of the name after the first dash is displayed
for eachfile in *;
do
    echo "$eachfile"
done
